apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: cerebros
  name: cerebros
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cerebros
    spec:
      containers:
      - image: lmenezes/cerebro
        name: cerebros
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
