mydb :
  image: mysql:5.7
  environment:
  - MYSQL_DATABASE=magento2
  - MYSQL_RANDOM_ROOT_PASSWORD=yes
  - MYSQL_USER=magento2
  - MYSQL_PASSWORD=!magento2
  volumes_from:
    - magento-data

web:
  image: meanbee/magento2-nginx:1.9
  links:
  - fpm
  volumes_from:
    - magento-data

fpm:
  image: meanbee/magento2-php:7.2-fpm
  links:
  - mydb
  volumes_from:
    - magento-data

cli:
  image: meanbee/magento2-php:7.2-cli
  command: ["/usr/local/bin/magento-installer"]
  environment:
  - M2SETUP_INSTALL_DB=false
  - M2SETUP_VERSION=2.3.1
  links:
  - mydb
  volumes_from:
    - magento-data

cron:
  image: meanbee/magento2-php:7.2-cli
  links:
  - mydb
  command: run-cron
  volumes_from:
    - magento-data

magento-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
    - /var/lib/mysql
    - /var/www/magento
    - ~/.composer/:/root/.composer/
  net: none
  command: /bin/true