version: '2'
catalog:
  name: "Magento2" # Name of the versioned template of the Catalog Entry
  version: 0 # Version of the versioned template of the Catalog Entry
  questions:
    - variable: "COMPOSER_GITHUB_TOKEN"
      label: "COMPOSER_GITHUB_TOKEN"
      description: ""
      required: false
      type: "string"
    - variable: "COMPOSER_MAGENTO_USERNAME"
      label: "COMPOSER_MAGENTO_USERNAME"
      description: ""
      required: false
      type: "string"
    - variable: "COMPOSER_MAGENTO_PASSWORD"
      label: "COMPOSER_MAGENTO_PASSWORD"
      description: ""
      required: false
      type: "string"
    - variable: "ARCHIVE"
      label: "ARCHIVE"
      description: ""
      required: false
      type: "string"
    - variable: "GIT"
      label: "GIT"
      description: ""
      required: false
      type: "string"
    - variable: "M2SETUP_VERSION"
      label: "M2SETUP_VERSION"
      description: ""
      default: "2.3.1"
      required: false
      type: "string"
    - variable: "M2SETUP_EDITION"
      label: "M2SETUP_EDITION"
      description: ""
      required: false
      default: "community"
      type: "enum"
      options:
        - community
        - enterprise
    - variable: "MYSQL_DATABASE"
      label: "MYSQL_DATABASE"
      description: ""
      default: "magento2"
      required: true
      type: "string"
    - variable: "MYSQL_USER"
      label: "MYSQL_USER"
      description: ""
      default: "yes"
      required: true
      type: "string"
    - variable: "MYSQL_PASSWORD"
      label: "MYSQL_PASSWORD"
      description: ""
      default: "!magento2"
      required: true
      type: "string"
    - variable: "M2SETUP_ADMIN_EMAIL"
      label: "M2SETUP_ADMIN_EMAIL"
      description: ""
      default: "email@example.com"
      required: true
      type: "string"
    - variable: "M2SETUP_ADMIN_PASSWORD"
      label: "M2SETUP_ADMIN_PASSWORD"
      description: ""
      default: "magento0"
      required: true
      type: "string"
    - variable: "DOMAIN"
      label: "DOMAIN"
      description: ""
      default: "magento.local"
      required: true
      type: "string"
    - variable: M2SETUP_INSTALL_DB
      label: "M2SETUP_INSTALL_DB"
      type: enum
      description: ""
      default: true
      options:
        - true
        - false
    - variable: M2SETUP_USE_SAMPLE_DATA
      label: "M2SETUP_USE_SAMPLE_DATA"
      type: enum
      description: ""
      default: "true"
      options:
        - "true"
        - "false"
    - variable: "COMPOSER_EXTRA_PACKAGES"
      label: "COMPOSER_EXTRA_PACKAGES"
      description: ""
      default: "smile/elasticsuite-for-retailer"
      required: false
      type: "string"