version: '3'

services:
  elasticsearch:
    build: https://raw.githubusercontent.com/EmakinaFR/docker-magento2/master/elasticsearch/Dockerfile
    ports:
    - 9200:9200
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name:"docker-cluster"
      - bootstrap.memory_lock="true"
      - ES_JAVA_OPTS=-Xms1096m -Xmx1096m
  
  cerebros:
    image: lmenezes/cerebro
    ports:
    - 9000:9000

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    depends_on:
    - elasticsearch
    ports:
    - 5601:5601
    environment:
    - ELASTIC_CONTAINER=true

volumes:
  esdata:
    driver: local
